# Generated by Django 3.2.8 on 2021-10-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=3)),
                ('customername', models.CharField(max_length=64)),
                ('startdate', models.DateField()),
                ('finishdate', models.DateField()),
            ],
        ),
    ]
