# Generated by Django 3.2.8 on 2021-10-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstreport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='city',
            field=models.CharField(max_length=64),
        ),
    ]
