# Generated by Django 3.2.8 on 2021-11-07 07:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('firstreport', '0005_remove_report_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='duration',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
