# Generated by Django 3.2.8 on 2021-11-07 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstreport', '0006_report_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='duration',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
