# Generated by Django 3.2.8 on 2021-11-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstreport', '0012_report_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
