# Generated by Django 3.2.8 on 2021-11-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstreport', '0013_alter_report_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='duration',
            field=models.DurationField(),
        ),
    ]
